### ISSUE TITLE
All methods are deleted

### ISSUE THREAD

**Issue by koeberlue** [jucham/clean-code-method-rearranger#1]
Given the attached code sample when I run "Rearrange Methods" then all methods are deleted by the plugin:

```
class DeleteMe {

    public void foo() {
        fooBar();
        fooBaz();
    }

    private void fooBar() {
        foobarStart();
        fooBarEnd();
    }

    private void foobarStart() {}

    private void fooBarEnd() {}

    private void fooBaz() {
        fooBazStart();
        fooBazEnd();
    }

    private void fooBazStart() {
        fooBazStartImpl();
    }

    private void fooBazStartImpl() {}

    private void fooBazEnd() {}

    public void helloWorld() {
        hello();
        world();
    }

    private void world() {}

    private void hello() {}
}
```

There are basically two public methods (`foo` and `helloWorld`) which call nested methods themselves. Everything except for the last two methods is already sorted correctly. IntelliJ does not report any errors.

Let me know if I can help tracking the problem down even further.

---

Intellij 2018.2.6
Clean Code Method Rearranger 0.1

**Comment by jucham** [comment]
Hello koeberlue, thank you for your feedback, much appreciated! I have fixed the problem and pushed it. The release of the fix is not yet available on JetBrain repo as I have some issues with publishing. However, I can provide it if you want to give a try.

**Comment by jucham** [comment]
The release of the fix is available now.

**Comment by koeberlue** [comment]
Great! It's working as expected now :+1:
